services:
  redis:
    image: redis:7-alpine
    container_name: pdf-microservice-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  pdf-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-microservice
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      PORT: 3000
      REDIS_URL: redis://redis:6379
      # Ajuste conforme necess√°rio
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:8081,http://localhost:8080}
      JSON_LIMIT: 50mb
      MAX_RETRIES: 3
    ports:
      - "3000:3000"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-gui
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data:
